# Secrets are provided by ./esphome-wrapper from an external SOPS file.
# The decrypted secrets.yaml is created only in a temporary directory outside this repository.
substitutions:
  name: ocpp
  static_ip: !secret static_ip

esp32:
  board: nodemcu-32s
  framework:
    type: esp-idf
    version: recommended

esphome:
  name: ${name}

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  manual_ip:
    static_ip: ${static_ip}
    gateway: !secret gateway
    subnet: !secret subnet
    dns1: !secret dns1

logger:

preferences:
  flash_write_interval: 1d

web_server:
  version: 3
  port: 80
  auth:
    username: admin
    password: admin


external_components:
  - components: [ ocpp ]
    source:
      type: local
      path: ./esphome/components

ocpp:
  id: ocpp_id
