# Secrets are provided by ./esphome-wrapper from an external SOPS file.
# The decrypted secrets.yaml is created only in a temporary directory outside this repository.
substitutions:
  name: ocpp
  static_ip: !secret static_ip

esp32:
  board: nodemcu-32s
  framework:
    type: esp-idf
    version: recommended

esphome:
  name: ${name}

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  manual_ip:
    static_ip: ${static_ip}
    gateway: !secret gateway
    subnet: !secret subnet
    dns1: !secret dns1

logger:

preferences:
  flash_write_interval: 1d

web_server:
  port: 80
  auth:
    username: !secret web_server_username
    password: !secret web_server_password

external_components:
  - components: [ ocpp ]
    source:
      type: local
      path: ./esphome/components

# mqtt:
#   broker: !secret mqtt_broker
#   username: !secret mqtt_username
#   password: !secret mqtt_password
#   reboot_timeout: 0s
#   keepalive: 5s


# sensor:
#   - platform: mqtt_subscribe
#     id: grid_power_l1
#     name: grid_power_l1
#     topic: inverter/sensor/grid_power_a/state
#     device_class: power
#     unit_of_measurement: "W"
#     accuracy_decimals: 0
#     filters:
#       - multiply: -1
#   - platform: mqtt_subscribe
#     id: grid_power_l2
#     name: grid_power_l2
#     topic: inverter/sensor/grid_power_b/state
#     device_class: power
#     unit_of_measurement: "W"
#     accuracy_decimals: 0
#     filters:
#       - multiply: -1
#   - platform: mqtt_subscribe
#     id: grid_power_l3
#     name: grid_power_l3
#     topic: inverter/sensor/grid_power_c/state
#     device_class: power
#     unit_of_measurement: "W"
#     accuracy_decimals: 0
#     filters:
#       - multiply: -1
#   - platform: mqtt_subscribe
#     id: storage_power
#     name: storage_power
#     topic: inverter/sensor/battery_power/state
#     device_class: power
#     unit_of_measurement: "W"
#     accuracy_decimals: 0
#   - platform: mqtt_subscribe
#     id: storage_soc
#     name: storage_soc
#     topic: inverter/sensor/battery_soc/state
#     device_class: energy
#     unit_of_measurement: "%"
#     accuracy_decimals: 0
#   - platform: mqtt_subscribe
#     id: storage_energy
#     name: storage_energy
#     topic: inverter/sensor/battery_energy_kwh/state
#     device_class: energy
#     unit_of_measurement: "kWh"
#     accuracy_decimals: 1


ocpp:
  id: ocpp_id
  phase_voltage: 230

  charge_points:
    - id: garage
      charge_point_id: A99999
      phases: 3
      max_current: 32
      debug_ocpp_messages: true
      debug_ocpp_exclude_actions:
        - MeterValues
      startup_notifications_delay: 5
      # protocol:
      #   name: garage_protocol
      # online:
      #   name: garage_online
      # charger_info:
      #   name: garage_charger_info
      connectors:
        - id: garage_1
          connector_id: 1
          log_meter_values: true
          status:
            name: 10_garage_status
          error:
            name: 11_garage_error
          plugged:
            name: 12_garage_plugged
          active_phases:
            name: 20_garage_active_phases
          current_limit:
            name: 30_garage_current_limit
          requested_current:
            name: 31_garage_requested_current
          current_l1:
            name: 41_garage_current_1
          current_l2:
            name: 42_garage_current_2
          current_l3:
            name: 43_garage_current_3
          power:
            name: 50_garage_power
          total_energy:
            name: 51_garage_total_energy
          session_time:
            name: 61_garage_session_time
          session_energy:
            name: 62_garage_session_energy
          # voltage_l1:
          #   name: garage_voltage_l1
          # voltage_l2:
          #   name: garage_voltage_l2
          # voltage_l3:
          #   name: garage_voltage_l3
    - id: unknown
      phases: 3
      max_current: 32
      debug_ocpp_messages: true
